import { useState } from 'react';
import GetStartedModal from '../components/GetStartedModal';
import {
CheckCircle,
Code2,
DollarSign,
ExternalLink,
FileText,
MapPin,
Megaphone,
MessageCircle,
Users,
Wrench,
} from "lucide-react";
import { motion } from 'framer-motion';
export default function LandscapingBusiness() {
const [isModalOpen, setIsModalOpen] = useState(false);
const [selectedBusinessType, setSelectedBusinessType] = useState
<string>
('');
interface Item {
title: string;
desc: string;
}
const Item: Item[] = [
{
title: "Obtain an Employer Identification Number (EIN)",
desc:
"Apply for an EIN so you can legally hire employees and handle payroll and tax reporting for your business.",
},
{
title: "Verify Employee Eligibility",
desc:
"Ensure that every new hire has the proper documentation to work legally in your country.",
},
{
title: "Report New Hires to State Agencies",
desc:
"Submit new employee details to state agencies for payroll and compliance purposes.",
},
{
title: "Set Up Payroll Tax Withholding",
desc:
"Calculate and withhold the correct payroll taxes for each employee and remit them to the government.",
},
{
title: "Create a Workplace Safety Plan",
desc:
"Establish safety protocols and provide training to reduce workplace accidents and comply with OSHA standards.",
},
{
title: "Establish Employment Policies",
desc:
"Draft employee handbooks covering attendance, code of conduct, leave policies, and other HR rules.",
},
{
title: "Choose Employee Benefits",
desc:
"Decide on benefits like health insurance, retirement plans, or paid time off to attract quality employees.",
},
{
title: "Provide Job Training",
desc:
"Offer proper training to ensure employees understand their responsibilities and your business standards.",
},
{
title: "Keep Accurate Records",
desc:
"Maintain up-to-date records of employee hours, pay, and other HR documentation to stay compliant.",
},
{
title: "Review and Improve Regularly",
desc:
"Regularly assess your hiring and HR practices to improve efficiency, compliance, and employee satisfaction.",
},
];
const tools = [
{
category: "Project Management",
items: [
{ name: "Asana", href: "https://asana.com" },
{ name: "Basecamp", href: "https://basecamp.com" },
{ name: "Trello", href: "https://trello.com" },
],
},
{
category: "Productivity",
items: [
{ name: "Todoist", href: "https://todoist.com" },
{ name: "Evernote", href: "https://evernote.com" },
],
},
{
category: "Collaboration",
items: [
{ name: "Google Docs", href: "https://docs.google.com" },
{ name: "Dropbox", href: "https://dropbox.com" },
{ name: "Box", href: "https://box.com" },
],
},
{
category: "Social Media Management",
items: [
{ name: "Hootsuite", href: "https://hootsuite.com" },
{ name: "Buffer", href: "https://buffer.com" },
{ name: "Sprout Social", href: "https://sproutsocial.com" },
{ name: "BuzzSumo", href: "https://buzzsumo.com" },
],
},
{
category: "Communication",
items: [
{ name: "Skype", href: "https://www.skype.com" },
{ name: "Slack", href: "https://slack.com" },
{ name: "Grasshopper", href: "https://grasshopper.com" },
],
},
{
category: "Email Marketing",
items: [
{ name: "MailChimp", href: "https://mailchimp.com" },
{ name: "Campaign Monitor", href: "https://campaignmonitor.com" },
],
},
{
category: "Advertising",
items: [
{ name: "Google Ads", href: "https://ads.google.com" },
{ name: "Bing Ads", href: "https://ads.microsoft.com" },
],
},
{
category: "CRM & Customer Support",
items: [
{ name: "SalesForce", href: "https://salesforce.com" },
{ name: "Zoho CRM", href: "https://zoho.com/crm" },
{ name: "Zendesk", href: "https://zendesk.com" },
{ name: "SurveyMonkey", href: "https://surveymonkey.com" },
],
},
{
category: "Human Resources",
items: [
{ name: "Gusto", href: "https://gusto.com" },
{ name: "Hire Athena", href: "https://hireathena.com" },
],
},
{
category: "Legal & Ecommerce",
items: [
{ name: "DocuSign", href: "https://docusign.com" },
{ name: "Wix", href: "https://wix.com" },
{ name: "Square", href: "https://squareup.com" },
],
},
{
category: "Website Development & SEO",
items: [
{ name: "Squarespace", href: "https://squarespace.com" },
{ name: "WordPress", href: "https://wordpress.org" },
{ name: "Google Analytics", href: "https://analytics.google.com" },
{ name: "Ahrefs", href: "https://ahrefs.com" },
],
},
];
const stats = [
{ value: "$800T", label: "Global landscaping industry revenue highlighting massive market potential" },
{ value: "4.8%", label: "Average annual industry growth rate showing steady expansion" },
{ value: "15%", label: "Revenue share generated by top landscaping companies" },
{ value: "$16B", label: "Annual spending on lawn care and gardening services by U.S. households" },
];
const industryInsights = [
"Over 500,000 landscaping businesses operate in the U.S., employing nearly 1 million professionals",
"Commercial landscaping contributes around 50% of total industry revenue, while residential services account for about 30%",
"Majority of businesses earn under $300K annually, while high-growth companies exceed $1M revenue",
"The landscaping and property services market is expected to grow consistently in the coming years",
];
const customerNeeds = [
"Landscape design & installation: strong portfolio, creativity, and trusted reputation",
"Lawn maintenance services: consistent, affordable, and high-quality service delivery",
"Residential clients: cost-effective solutions with maximum value",
"Commercial clients: fast, reliable, and scalable service execution",
];
const skills = [
"Hiring and building a skilled landscaping team",
"Effective staff and operations management",
"Local marketing and brand positioning strategies",
"Competitive service pricing with profitable margins",
"Business setup including tools, vehicles, and resources",
"Delivering high-quality operational services",
"Managing finances, payroll, and business administration",
];
const steps = [
{
title: "Analyze Landscaping Market Demand",
description:
"Research local, national, and global landscaping industry trends to identify demand for your services and uncover profitable opportunities.",
},
{
title: "Evaluate Competitors",
description:
"Study existing landscaping businesses in your area to understand their services, pricing, and positioning to identify market gaps.",
},
{
title: "Understand Customer Needs",
description:
"Connect with potential clients to learn about their landscaping requirements, preferences, and expectations for quality and pricing.",
},
{
title: "Define Your Unique Selling Proposition (USP)",
description:
"Differentiate your landscaping business with competitive pricing, superior service quality, faster delivery, or specialized offerings.",
},
{
title: "Engage with Business Communities",
description:
"Join landscaping forums, local business groups, and industry discussions to gain insights, ask questions, and build valuable connections.",
},
];
const modelPoints = [
"Define a clear landscaping business model to generate consistent revenue and deliver high-quality services",
"Plan your pricing strategy, service offerings, and customer acquisition process for long-term growth",
"Focus on recurring revenue streams such as lawn care and maintenance contracts",
];
const financialPoints = [
"Estimate monthly, quarterly, and yearly revenue projections",
"Analyze profitability, operating costs, and growth investments",
"Plan salary distribution for yourself and your team",
"Reinvest profits strategically to scale your landscaping business",
];
const businessPlanPoints = [
"Executive summary highlighting key business objectives",
"Clear business goals and long-term vision",
"Company overview with background and market positioning",
"Detailed market analysis and demand forecasting",
"Business structure and operational framework",
"Revenue model and service strategy",
"Marketing and sales approach",
"Financial projections and profitability analysis",
"Supporting documents and appendices",
];
const businessStructures = [
  {
    title: "Sole Proprietorship",
    description:
      "A basic business structure with minimal setup, but no legal separation between personal and business assets, making it risky for long-term growth.",
  },
  {
    title: "Limited Liability Company (LLC)",
    description:
      "The most popular choice for landscaping businesses, offering liability protection, flexibility, and simple management with cost-effective setup.",
  },
  {
    title: "Series LLC",
    description:
      "An advanced LLC structure available in select regions, allowing multiple business units with separate liabilities under one parent entity.",
  },
  {
    title: "S Corporation",
    description:
      "A structured business entity offering tax advantages but requiring stricter compliance, suitable for growing businesses.",
  },
  {
    title: "C Corporation",
    description:
      "A complex corporate structure ideal for large-scale enterprises, investors, and high-growth companies.",
  },
];
const considerations = [
  "Choose a business structure that protects your personal assets and supports growth",
  "Understand legal, tax, and compliance requirements before registration",
  "LLCs are typically the best choice for small to medium landscaping businesses",
  "Business registration requirements may vary based on location",
  "Consult professional guidance to ensure correct business formation",
];
const setupSteps = [
  {
    icon: MapPin,
    title: "Choose the Right Business Location",
    description:
      "Decide whether to operate your landscaping business from home, an office, or a commercial space. Ensure you have adequate storage for tools, equipment, and materials to run operations efficiently.",
  },
  {
    icon: Megaphone,
    title: "Build a Strong Marketing Strategy",
    description:
      "Create a professional website and focus on local SEO and digital marketing to attract customers and grow your landscaping business in your target area.",
  },
  {
    icon: FileText,
    title: "Manage Business Compliance & Maintenance",
    description:
      "Stay compliant by filing annual reports, renewing licenses, and managing permits. Keep track of estimated taxes and ensure your business meets all legal requirements.",
  },
  {
    icon: Code2,
    title: "Use Landscaping Business Software",
    description:
      "Leverage modern software tools to streamline scheduling, customer management, invoicing, and overall business operations for improved efficiency.",
  },
  {
    icon: Wrench,
    title: "Invest in Essential Equipment",
    description:
      "Equip your business with the right tools such as lawnmowers, trimmers, and installation equipment based on your services. Plan expenses carefully for better financial management.",
  },
  {
    icon: DollarSign,
    title: "Set Up Finances & Tax Planning",
    description:
      "Open a business bank account, manage cash flow, and plan your taxes effectively to ensure profitability and long-term financial stability.",
  },
  {
    icon: Users,
    title: "Plan Hiring & Workforce Strategy",
    description:
      "Start lean by working with freelancers or contractors, and gradually build a skilled team as your landscaping business grows.",
  },
];
const hiringSteps = [
  "Apply for an Employer Identification Number (EIN) to manage employee taxes and payroll legally",
  "Verify employee eligibility to work in compliance with local labor laws and regulations",
  "Register and report all new hires to the appropriate government authorities",
  "Properly withhold income tax and payroll taxes to stay compliant with tax regulations",
  "Secure workers’ compensation insurance to protect your business and employees",
  "Establish a consistent payroll system to pay employees accurately and on time",
  "Understand employment laws, responsibilities, and workplace compliance requirements",
];
const communities = [
  {
    name: "Lawnsite",
    url: "https://www.lawnsite.com",
    description:
      "A top landscaping forum for lawn care professionals to discuss business growth, equipment, pricing, and marketing strategies.",
  },
  {
    name: "Ground Trades Xchange",
    url: "https://www.groundtradesxchange.com",
    description:
      "A professional community for landscaping and grounds maintenance experts to share industry insights and business tips.",
  },
  {
    name: "Lawn Service Forum",
    url: "https://www.lawnserviceforum.com",
    description:
      "An active lawn care business forum focused on customer acquisition, service pricing, and operational efficiency.",
  },
  {
    name: "Gopher Lawn Care Business Forum",
    url: "https://www.gopherforum.com",
    description:
      "A popular landscaping business resource offering expert advice on starting, managing, and scaling your services.",
  },
  {
    name: "Lawncare & Landscaping Forum",
    url: "https://www.lawncareforum.com",
    description:
      "A community-driven platform where landscaping professionals exchange ideas, tools, and best practices.",
  },
  {
    name: "Contractor Talk - Landscaping",
    url: "https://www.contractortalk.com/forums/landscaping.20/",
    description:
      "A trusted contractor community covering landscaping projects, client management, and business development strategies.",
  },
];
return (
<div className="min-h-screen bg-white">
   {/* HERO */}
   <section className="relative w-full py-16 flex items-center justify-center overflow-hidden">
      {/* Background Image */}
      <div className="absolute inset-0">
         <img
            src="https://images.unsplash.com/photo-1592595896616-c37162298647?auto=compress&cs=tinysrgb&w=1920"
            alt="Landscaping business garden"
            className="w-full h-full object-cover"
            />
         <div className="absolute inset-0 bg-black/70"></div>
      </div>
      {/* Content */}
      <div className="relative z-10 max-w-6xl text-center px-6 text-white">
         <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold leading-tight mb-6">
            How to Start a <span className="text-cyan-500">Landscaping Business</span>
         </h1>
         <p className="text-lg sm:text-xl text-gray-300 mb-6 leading-relaxed">
            Everyone wants a beautiful outdoor space. From well-designed gardens to properly maintained lawns, landscaping services play a key role in enhancing homes and environments.
         </p>
         <p className="text-gray-400 mb-10 max-w-3xl mx-auto">
            This creates a profitable opportunity for entrepreneurs. If you can deliver high-quality lawn care, garden design, and landscaping services, you can successfully build and grow a thriving local landscaping business.
         </p>
         {/* CTA */}
         <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button onClick={() => {
            setSelectedBusinessType('');
            setIsModalOpen(true);
            }} className="px-8 py-3 bg-cyan-500 hover:bg-cyan-600 rounded-xl font-semibold transition shadow-lg shadow-cyan-500/30">
            Start Your Landscaping Business
            </button>
            <button className="px-8 py-3 border border-white/30 hover:border-white rounded-xl font-semibold transition">
            Learn More
            </button>
         </div>
      </div>
      {/* Bottom Fade */}
      <div className="absolute bottom-0 left-0 w-full h-32 bg-gradient-to-t from-black to-transparent"></div>
   </section>
   <section className="py-16 px-6 bg-gradient-to-b from-gray-50 to-white text-gray-900">
      <div className="max-w-7xl mx-auto">
         {/* Header */}
         <motion.div
         initial={{ opacity: 0, y: 20 }}
         whileInView={{ opacity: 1, y: 0 }}
         transition={{ duration: 0.5 }}
         className="max-w-6xl mb-6 text-center mx-auto"
         >
         <h2 className="text-4xl md:text-5xl font-extrabold leading-tight mb-4">
            Start a <span className="text-cyan-600">Landscaping Business</span> & Grow Fast
         </h2>
         <p className="text-gray-600 text-lg leading-relaxed">
            Build a profitable landscaping business with services like lawn care, garden design, yard maintenance, and outdoor beautification. Whether you're a beginner or experienced entrepreneur, this industry offers strong growth opportunities.
         </p>
         </motion.div>
         {/* Main Grid */}
         <div className="grid lg:grid-cols-2 gap-10 items-stretch">
            {/* Left Content Card */}
            <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
            className="bg-white border border-gray-200 rounded-2xl p-8 shadow-sm hover:shadow-md transition"
            >
            <p className="text-gray-600 mb-6 leading-relaxed">
               High-end landscaping design requires professional expertise, specialized tools, and a skilled team, making it a higher investment business. However, lawn maintenance and basic services can be started with minimal cost, making it ideal for beginners.
            </p>
            <p className="text-gray-600 mb-6 leading-relaxed">
               This flexibility makes landscaping a perfect business for all skill levels—from individuals starting small to professionals scaling a full-service company.
            </p>
            {/* Image Section */}
            <div className="mt-4 overflow-hidden rounded-xl">
               <img
                  src="https://images.unsplash.com/photo-1758501395624-de0bce47d124?q=80"
                  alt="Landscaping Business"
                  className="w-full h-48 object-cover rounded-xl hover:scale-105 transition duration-300"
                  />
            </div>
            </motion.div>
            {/* Right Feature List */}
            <motion.div
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
            className="bg-white border border-gray-200 rounded-2xl p-8 shadow-sm hover:shadow-md transition"
            >
            <h3 className="text-2xl font-bold mb-6 text-gray-900">
               What You’ll Learn
            </h3>
            <ul className="space-y-4 text-gray-600 text-sm">
               {[
               "Understanding the landscaping industry & market trends",
               "Step-by-step guide to start a landscaping business",
               "Taxes, licenses & legal requirements",
               "Hiring employees & managing operations",
               "Financial planning & business growth strategies",
               "Tools, resources & support systems",
               "Choosing the right legal structure",
               "Compliance with rules & regulations",
               "And much more...",
               ].map((item, i) => (
               <li key={i} className="flex text-base items-start gap-3">
                  <span className="mt-1 w-2 h-2 bg-cyan-500 rounded-full"></span>
                  <span>{item}</span>
               </li>
               ))}
            </ul>
            </motion.div>
         </div>
         {/* CTA */}
         <motion.div
         initial={{ opacity: 0, y: 20 }}
         whileInView={{ opacity: 1, y: 0 }}
         transition={{ duration: 0.5 }}
         className="mt-10 bg-cyan-600 rounded-2xl py-10 text-center"
         > 
         <p className="text-white mb-6 max-w-2xl mx-auto">
            By the end of this complete guide, you'll have everything needed to start, manage, and scale a successful landscaping business.
         </p>
         <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button onClick={() => {
            setSelectedBusinessType('');
            setIsModalOpen(true);
            }} className="px-8 py-3 bg-slate-700 hover:bg-cyan-700 text-white rounded-xl font-semibold transition shadow-sm">
            Start Your Business
            </button>
         </div>
         </motion.div>
      </div>
   </section>
   <section className="relative py-16 bg-cyan-50">
      <div className="max-w-7xl mx-auto px-6">
         {/* Header */}
         <motion.div
         initial={{ opacity: 0, y: 40 }}
         whileInView={{ opacity: 1, y: 0 }}
         transition={{ duration: 0.5 }}
         className="text-center mb-10"
         >
         <h2 className="text-5xl font-extrabold text-gray-900 mb-4">
            <span className='text-cyan-600'>Landscaping Business Guide:</span> Market Insights, Opportunities & Growth Strategy
         </h2>
         <p className="text-gray-600 max-w-3xl mx-auto text-lg">
            Discover key landscaping industry statistics, customer expectations, and essential business skills to successfully start and grow a profitable landscaping company in a competitive market.
         </p>
         </motion.div>
         {/* Stats */}
         <div className="grid md:grid-cols-4 gap-6 mb-10">
            {stats.map((stat, i) => (
            <motion.div
            key={i}
            whileHover={{ scale: 1.05 }}
            className="bg-white rounded-2xl shadow-sm p-6 text-center border border-gray-200 hover:shadow-md transition"
            >
            <h3 className="text-2xl font-bold text-cyan-600 mb-2">
               {stat.value}
            </h3>
            <p className="text-gray-600 text-sm">{stat.label}</p>
            </motion.div>
            ))}
         </div>
         {/* Grid Sections */}
         <div className="grid md:grid-cols-3 gap-8">
            {/* Industry Insights */}
            <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-200 hover:shadow-md transition">
               <h3 className="text-xl font-semibold mb-4 text-gray-900">
                  Industry Insights & Opportunities
               </h3>
               <ul className="space-y-3">
                  {industryInsights.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-gray-600 text-sm">
                     <CheckCircle className="w-4 h-4 text-cyan-500 mt-1" />
                     {item}
                  </li>
                  ))}
               </ul>
            </div>
            {/* Customer Needs */}
            <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-200 hover:shadow-md transition">
               <h3 className="text-xl font-semibold mb-4 text-gray-900">
                  What Landscaping Customers Expect
               </h3>
               <ul className="space-y-3">
                  {customerNeeds.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-gray-600 text-sm">
                     <CheckCircle className="w-4 h-4 text-cyan-500 mt-1" />
                     {item}
                  </li>
                  ))}
               </ul>
            </div>
            {/* Skills */}
            <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-200 hover:shadow-md transition">
               <h3 className="text-xl font-semibold mb-4 text-gray-900">
                  Essential Skills for Landscaping Entrepreneurs
               </h3>
               <ul className="space-y-3">
                  {skills.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-gray-600 text-sm">
                     <CheckCircle className="w-4 h-4 text-cyan-500 mt-1" />
                     {item}
                  </li>
                  ))}
               </ul>
            </div>
         </div>
      </div>
   </section>
   <section className="relative py-16 bg-white">
      <div className="max-w-7xl mx-auto px-6">
         {/* Header */}
         <motion.div
         initial={{ opacity: 0, y: 40 }}
         whileInView={{ opacity: 1, y: 0 }}
         transition={{ duration: 0.5 }}
         className="text-center mb-14"
         >
         <h2 className="text-5xl font-extrabold text-gray-900 mb-4">
            How to Plan a Successful <span className='text-cyan-600'>Landscaping Business</span>
         </h2>
         <p className="text-gray-600 max-w-3xl mx-auto text-lg">
            Build a strong foundation for your landscaping business with effective planning, market research, and strategic positioning to ensure long-term growth and profitability.
         </p>
         </motion.div>
         {/* Content Grid */}
         <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {steps.map((step, i) => (
            <motion.div
            key={i}
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: i * 0.1 }}
            whileHover={{ y: -6 }}
            className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition"
            >
            <div className="flex items-start gap-3 mb-4">
               <CheckCircle className="text-cyan-600 w-5 h-5 mt-1" />
               <h3 className="text-lg font-semibold text-gray-900">
                  {step.title}
               </h3>
            </div>
            <p className="text-gray-600 text-sm leading-relaxed">
               {step.description}
            </p>
            </motion.div>
            ))}
         </div>
         {/* CTA */}
         <motion.div
         initial={{ opacity: 0, y: 40 }}
         whileInView={{ opacity: 1, y: 0 }}
         transition={{ duration: 0.5 }}
         className="text-center mt-10"
         >
         <p className="text-gray-600 max-w-2xl mx-auto mb-6">
            A well-planned landscaping business backed by strong market research and clear strategy can help you stand out in a competitive market and achieve sustainable success.
         </p>
         <a href="/contact" className="px-6 py-3 bg-cyan-600 text-white rounded-xl font-medium hover:bg-cyan-700 transition">
         Start Planning Your Landscaping Business
         </a>
         </motion.div>
      </div>
   </section>
   <section className="relative py-16 bg-cyan-50">
      <div className="max-w-7xl mx-auto px-6">
         {/* Header */}
         <motion.div
         initial={{ opacity: 0, y: 40 }}
         whileInView={{ opacity: 1, y: 0 }}
         transition={{ duration: 0.5 }}
         className="text-center mb-14"
         >
         <h2 className="text-5xl font-extrabold text-gray-900 mb-4">
            <span className='text-cyan-600'>Landscaping Business</span> Model, Financial Planning & Growth Strategy
         </h2>
         <p className="text-gray-600 max-w-3xl mx-auto text-lg">
            Build a profitable landscaping business with a strong business model,
            accurate financial projections, and a well-structured business plan
            designed for long-term success and scalable growth.
         </p>
         </motion.div>
         {/* Sections */}
         <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* Business Model */}
            <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            whileHover={{ y: -6 }}
            transition={{ duration: 0.4 }}
            className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition"
            >
            <h3 className="text-xl font-semibold mb-4 text-gray-900">
               Business Model Strategy
            </h3>
            <ul className="space-y-3">
               {modelPoints.map((item, i) => (
               <li key={i} className="flex items-start gap-2 text-gray-600 text-sm">
                  <CheckCircle className="w-4 h-4 text-cyan-600 mt-1" />
                  {item}
               </li>
               ))}
            </ul>
            </motion.div>
            {/* Financial Planning */}
            <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            whileHover={{ y: -6 }}
            transition={{ duration: 0.4 }}
            className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition"
            >
            <h3 className="text-xl font-semibold mb-4 text-gray-900">
               Financial Projections & Revenue Planning
            </h3>
            <ul className="space-y-3">
               {financialPoints.map((item, i) => (
               <li key={i} className="flex items-start gap-2 text-gray-600 text-sm">
                  <CheckCircle className="w-4 h-4 text-cyan-600 mt-1" />
                  {item}
               </li>
               ))}
            </ul>
            </motion.div>
            {/* Business Plan */}
            <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            whileHover={{ y: -6 }}
            transition={{ duration: 0.4 }}
            className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition"
            >
            <h3 className="text-xl font-semibold mb-4 text-gray-900">
               Complete Landscaping Business Plan
            </h3>
            <ul className="space-y-3">
               {businessPlanPoints.map((item, i) => (
               <li key={i} className="flex items-start gap-2 text-gray-600 text-sm">
                  <CheckCircle className="w-4 h-4 text-cyan-600 mt-1" />
                  {item}
               </li>
               ))}
            </ul>
            </motion.div>
         </div>
         {/* CTA */}
         <motion.div
         initial={{ opacity: 0, y: 40 }}
         whileInView={{ opacity: 1, y: 0 }}
         transition={{ duration: 0.5 }}
         className="text-center mt-16"
         >
         <p className="text-gray-600 max-w-2xl mx-auto mb-6">
            A well-defined business model combined with strong financial planning
            can help you build a scalable and profitable landscaping business in a competitive market.
         </p>
         <button onClick={() => {
         setSelectedBusinessType('');
         setIsModalOpen(true);
         }} className="px-8 py-4 bg-cyan-600 text-white rounded-xl font-bold hover:bg-cyan-700 transition">
         Get Started Now
         </button>
         </motion.div>
      </div>
   </section>
    <section className="relative py-16 bg-white">
      <div className="max-w-7xl mx-auto px-6">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-14"
        >
          <h2 className="text-5xl font-extrabold text-gray-900 mb-4">
            Choose the Right <span className='text-cyan-600'>Landscaping Business</span> Structure & Register Your Company
          </h2>
          <p className="text-gray-600 max-w-3xl mx-auto text-lg">
            Select the best legal structure for your landscaping business to protect your assets,
            optimize taxes, and build a strong foundation for long-term growth and success.
          </p>
        </motion.div>

        {/* Cards */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 mb-10">
          {businessStructures.map((item, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              whileHover={{ y: -6 }}
              transition={{ duration: 0.4, delay: i * 0.05 }}
              className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition"
            >
              <h3 className="text-lg font-bold text-gray-900 mb-3">
                {item.title}
              </h3>
              <p className="text-gray-600 text-sm leading-relaxed">
                {item.description}
              </p>
            </motion.div>
          ))}
        </div>

        {/* Considerations */}
        <div className="bg-white border border-gray-200 rounded-2xl p-8 shadow-sm hover:shadow-md transition mb-16">
          <h3 className="text-xl font-bold text-gray-900 mb-6 text-center">
            Key Considerations for Landscaping Business Registration
          </h3>
          <div className="grid md:grid-cols-2 gap-4">
            {considerations.map((item, i) => (
              <div key={i} className="flex items-start gap-3 text-gray-600 text-sm">
                <CheckCircle className="w-5 h-5 text-cyan-600 mt-1" />
                {item}
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center"
        >
          <p className="text-gray-600 max-w-2xl mx-auto mb-6">
            Register your landscaping business with the right structure to ensure legal protection,
            financial security, and scalable growth in a competitive market.
          </p>
          <button className="px-6 py-3 bg-cyan-600 text-white rounded-xl font-medium hover:bg-cyan-700 transition">
            Start Your Landscaping Business Today
          </button>
        </motion.div>
      </div>
    </section>
    <section className="relative py-16 bg-cyan-50">
      <div className="max-w-7xl mx-auto px-6">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-14"
        >
          <h2 className="text-5xl font-extrabold text-gray-900 mb-4">
            Complete Guide to Setting Up a Successful <span className='text-cyan-600'>Landscaping Business</span>
          </h2>
          <p className="text-gray-600 max-w-3xl mx-auto text-lg">
            Learn how to set up your landscaping business with the right location,
            marketing strategy, tools, financial planning, and operational systems
            to ensure long-term success and growth.
          </p>
        </motion.div>

        {/* Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {setupSteps.map((item, i) => {
            const Icon = item.icon;
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                whileHover={{ y: -6 }}
                transition={{ duration: 0.4, delay: i * 0.05 }}
                className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition"
              >
                <div className="flex items-start gap-4 mb-4">
                  <div className="p-3 rounded-xl bg-cyan-100 text-cyan-600">
                    <Icon className="w-5 h-5" />
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900">
                    {item.title}
                  </h3>
                </div>
                <p className="text-gray-600 text-sm leading-relaxed">
                  {item.description}
                </p>
              </motion.div>
            );
          })}
        </div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mt-16"
        >
          <p className="text-gray-600 max-w-2xl mx-auto mb-6">
            Set up your landscaping business the right way with proper planning,
            tools, and strategies to build a scalable and profitable venture.
          </p>
          <button className="px-6 py-3 bg-cyan-600 text-white rounded-xl font-medium hover:bg-cyan-700 transition">
            Launch Your Landscaping Business
          </button>
        </motion.div>
      </div>
    </section>
    <section className="relative py-16 bg-gradient-to-br from-cyan-50 via-white to-cyan-50">
      <div className="max-w-7xl mx-auto px-6">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-14"
        >
          <div className="flex justify-center mb-4">
            <div className="p-4 rounded-2xl bg-cyan-100 text-cyan-600">
              <Users className="w-6 h-6" />
            </div>
          </div>
          <h2 className="text-5xl font-extrabold text-gray-900 mb-4">
            Hiring Employees for Your <span className='text-cyan-600'>Landscaping Business</span> : Complete Compliance Guide
          </h2>
          <p className="text-gray-600 max-w-3xl mx-auto text-lg">
            Build a reliable landscaping team by following proper hiring processes, legal compliance,
            and payroll management to ensure smooth operations and long-term business growth.
          </p>
        </motion.div>

        {/* Content */}
        <div className="max-w-4xl mx-auto bg-white border border-gray-200 rounded-2xl p-8 shadow-sm hover:shadow-md transition">
          <ul className="space-y-4">
            {hiringSteps.map((step, i) => (
              <motion.li
                key={i}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.4, delay: i * 0.05 }}
                className="flex items-start gap-3 text-gray-700"
              >
                <CheckCircle className="w-5 h-5 text-cyan-600 mt-1" />
                <span className="text-sm md:text-base leading-relaxed">
                  {step}
                </span>
              </motion.li>
            ))}
          </ul>
        </div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mt-16"
        >
          <p className="text-gray-600 max-w-2xl mx-auto mb-6">
            Hiring the right employees with proper legal compliance ensures your landscaping business
            runs efficiently, minimizes risks, and supports long-term scalability.
          </p>
          <button className="px-6 py-3 bg-cyan-600 text-white rounded-xl font-medium hover:bg-cyan-700 transition">
            Build Your Landscaping Team Today
          </button>
        </motion.div>
      </div>
    </section>
    <section className="relative py-16 bg-cyan-50">
      <div className="max-w-7xl mx-auto px-6">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <div className="flex justify-center mb-5">
            <div className="p-4 rounded-2xl bg-cyan-100 text-cyan-600">
              <Users className="w-6 h-6" />
            </div>
          </div>

          <h2 className="text-5xl font-extrabold text-gray-900 mb-4">
            Top Landscaping Forums & Online Communities for <span className='text-cyan-600'>Business Growth</span>
          </h2>

          <p className="text-gray-600 max-w-3xl mx-auto text-lg leading-relaxed">
            Connect with the best landscaping forums, lawn care communities, and contractor networks to gain expert insights, improve marketing strategies, and scale your landscaping business effectively.
          </p>
        </motion.div>

        {/* Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {communities.map((item, i) => (
            <motion.a
              key={i}
              href={item.url}
              target="_blank"
              rel="noopener noreferrer"
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              whileHover={{ y: -8 }}
              transition={{ duration: 0.4, delay: i * 0.05 }}
              className="group bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-xl transition-all duration-300 block"
            >
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className="p-3 rounded-xl bg-cyan-100 text-cyan-600 group-hover:bg-cyan-600 group-hover:text-white transition">
                    <MessageCircle className="w-5 h-5" />
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900">
                    {item.name}
                  </h3>
                </div>
                <ExternalLink className="w-4 h-4 text-gray-400 group-hover:text-cyan-600 transition" />
              </div>

              <p className="text-gray-600 text-sm leading-relaxed">
                {item.description}
              </p>

              <div className="mt-5 text-sm font-medium text-cyan-600 group-hover:underline">
                Visit Community
              </div>
            </motion.a>
          ))}
        </div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mt-20"
        >
          <p className="text-gray-600 max-w-2xl mx-auto mb-6 text-lg">
            Join these top landscaping communities to learn from industry experts, discover new opportunities, and grow your lawn care business faster.
          </p>

          <button
            onClick={() => {
            setSelectedBusinessType('');
            setIsModalOpen(true);
            }}
            className="inline-block px-8 py-3 bg-cyan-600 text-white rounded-xl font-semibold hover:bg-cyan-700 transition-all shadow-md hover:shadow-lg"
          >
            Explore More Resources
          </button>
        </motion.div>
      </div>
    </section>
   <section className="w-full bg-white py-20">
      <div className="max-w-6xl mx-auto px-6">
         {/* Heading */}
         <h2 className="text-5xl font-extrabold text-gray-900 text-center">
            Useful Online Tools for Your <span className='text-cyan-600'>Landscaping Business</span>
         </h2>
         {/* Description */}
         <p className="mt-4 text-lg text-gray-600 text-center max-w-3xl mx-auto">
            These online tools can help you streamline admin tasks, improve
            productivity, handle marketing, and grow your landscaping business.
         </p>
         {/* Tools List */}
         <div className="mt-12 space-y-12">
            {tools.map((section, idx) => (
            <div key={idx}>
               <h3 className="text-2xl font-bold text-cyan-600 mb-4">
                  {section.category}
               </h3>
               <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {section.items.map((tool, index) => (
                  <a
                     key={index}
                     href={tool.href}
                     target="_blank"
                     rel="noopener noreferrer"
                     className="flex justify-between items-center px-5 py-4 bg-gray-50 rounded-lg border border-gray-200 hover:bg-white transition"
                     >
                  <span className="text-gray-800 font-bold">{tool.name}</span>
                  <span className="text-cyan-600 text-xl">→</span>
                  </a>
                  ))}
               </div>
            </div>
            ))}
         </div>
      </div>
   </section>
   <GetStartedModal
      isOpen={isModalOpen}
      onClose={() =>
   setIsModalOpen(false)}
   selectedBusinessType={selectedBusinessType}
   />
</div>
);
}